### ISSUE TITLE
编译参数不明或目录结构有误

### ISSUE THREAD

**Issue by Tymon42** [leaper-one/2someone-proto#5]
当前目录结构形如：
```
start/
├── buf.gen.yaml
├── gen
│   └── proto
│       └── go
│           └── note *1
│               └── v1
│                   ├── note.pb.go
│                   └── note_grpc.pb.go
└── note *2
            └── note.proto
```
但是执行 `buf generate` 后，*1 处并没有形成相应的目录结构，而是在 *1 上级目录平行生成 pb.go 文件
有以下问题不明或代办：
1. 正常的编译指令是什么，需完善到 README.md;  
2. *2 处是否需要形如：
```
│           └── note
│               └── v1
│                   └── note.proto
```
的目录结构？

**Comment by Tymon42** [comment]
@kunzituheche

**Comment by kunzituheche** [comment]
*1处没有形成文件的原因是在需要在buf.gen.yaml中的配置的plugins标签下更改out：gen/proto/go/xxx/v1,一会我把两个buf相关的两个yaml文件配置说明传上来。另外参考到版本迭代问题，.proto也放在v1级目录下吧。
> @kunzituheche

**Comment by Tymon42** [comment]
我建议按照 #6 的方式重新组织 .proto 的结构，这样既不用反复设置 out 参数，还能体现每个服务所属的模块、体现业务之间的联系。

**Comment by Tymon42** [comment]
你在本地试试 #6 的方案可不可行，以及与你方案做一下横向对比。
